version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "${MYSQL_PORT}:3306"
