version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
