@startuml
title Ticketing

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary("Application.Application_boundary", "Application", $tags="") {
  Component(Application.Application.SharedKernel, "Shared Kernel", "Module", "", $tags="")
  Component(Application.Application.Ticketing, "Ticketing", "Module", "", $tags="")
  Component(Application.Application.Catalog, "Catalog", "Module", "", $tags="")
}

Rel_D(Application.Application.Ticketing, Application.Application.SharedKernel, "listens to", $tags="")
Rel_D(Application.Application.Ticketing, Application.Application.Catalog, "uses", $tags="")
Rel_D(Application.Application.Ticketing, Application.Application.SharedKernel, "uses", $tags="")
Rel_D(Application.Application.Catalog, Application.Application.SharedKernel, "depends on", $tags="")

SHOW_LEGEND(true)
@enduml