server:
  port: 8080

spring:
  application:
    name: event-ticketing-system

  datasource:
    url: jdbc:mysql://db:3306/ticketing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    org.springframework: INFO
